-- Portfolio Manager MySQL 8.0 bootstrap schema
-- Design status: proposed implementation baseline
-- UUID values are generated by the application and stored as canonical strings.
-- All DATETIME values are written and read as UTC.
-- This script is non-destructive and does not drop existing tables or data.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE DATABASE IF NOT EXISTS portfolio_manager
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

USE portfolio_manager;

CREATE TABLE IF NOT EXISTS app_user (
    id              char(36) NOT NULL,
    email           varchar(320) NOT NULL,
    display_name    varchar(120) NOT NULL,
    is_active       boolean NOT NULL DEFAULT true,
    created_at      datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
                    ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT app_user_email_not_blank CHECK (TRIM(email) <> ''),
    CONSTRAINT app_user_display_name_not_blank
        CHECK (TRIM(display_name) <> '')
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS portfolio (
    id              char(36) NOT NULL,
    user_id         char(36) NOT NULL,
    name            varchar(120) NOT NULL,
    description     varchar(500),
    base_currency   char(3) NOT NULL DEFAULT 'USD',
    is_archived     boolean NOT NULL DEFAULT false,
    active_name     varchar(120)
                    GENERATED ALWAYS AS (
                        CASE
                            WHEN is_archived = false THEN LOWER(name)
                            ELSE NULL
                        END
                    ) STORED,
    created_at      datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
                    ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_portfolio_user
        FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_portfolio_user_active_name
        UNIQUE (user_id, active_name),
    CONSTRAINT portfolio_name_not_blank CHECK (TRIM(name) <> ''),
    CONSTRAINT portfolio_base_currency_format
        CHECK (
            CHAR_LENGTH(base_currency) = 3
            AND BINARY base_currency = BINARY UPPER(base_currency)
        ),
    KEY ix_portfolio_user_active (user_id, is_archived)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS instrument (
    id              char(36) NOT NULL,
    symbol          varchar(32) NOT NULL,
    name            varchar(200) NOT NULL,
    asset_type      enum('STOCK', 'ETF') NOT NULL,
    exchange_code   varchar(32) NOT NULL,
    currency        char(3) NOT NULL DEFAULT 'USD',
    provider_symbol varchar(64),
    is_active       boolean NOT NULL DEFAULT true,
    created_at      datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
                    ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_instrument_exchange_symbol
        UNIQUE (exchange_code, symbol),
    CONSTRAINT instrument_symbol_not_blank CHECK (TRIM(symbol) <> ''),
    CONSTRAINT instrument_symbol_uppercase
        CHECK (BINARY symbol = BINARY UPPER(symbol)),
    CONSTRAINT instrument_name_not_blank CHECK (TRIM(name) <> ''),
    CONSTRAINT instrument_exchange_not_blank
        CHECK (TRIM(exchange_code) <> ''),
    CONSTRAINT instrument_currency_format
        CHECK (
            CHAR_LENGTH(currency) = 3
            AND BINARY currency = BINARY UPPER(currency)
        ),
    KEY ix_instrument_symbol_active (symbol, is_active)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS trade_transaction (
    id                  char(36) NOT NULL,
    portfolio_id        char(36) NOT NULL,
    instrument_id       char(36) NOT NULL,
    side                enum('BUY', 'SELL') NOT NULL,
    quantity            decimal(28, 8) NOT NULL,
    unit_price          decimal(20, 8) NOT NULL,
    fee_amount          decimal(20, 8) NOT NULL DEFAULT 0,
    currency            char(3) NOT NULL DEFAULT 'USD',
    executed_at         datetime(6) NOT NULL,
    idempotency_key     varchar(100) NOT NULL,
    note                varchar(500),
    created_at          datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_trade_portfolio
        FOREIGN KEY (portfolio_id)
        REFERENCES portfolio (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_trade_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES instrument (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_trade_portfolio_idempotency
        UNIQUE (portfolio_id, idempotency_key),
    CONSTRAINT trade_quantity_positive CHECK (quantity > 0),
    CONSTRAINT trade_unit_price_positive CHECK (unit_price > 0),
    CONSTRAINT trade_fee_nonnegative CHECK (fee_amount >= 0),
    CONSTRAINT trade_currency_format
        CHECK (
            CHAR_LENGTH(currency) = 3
            AND BINARY currency = BINARY UPPER(currency)
        ),
    CONSTRAINT trade_idempotency_key_not_blank
        CHECK (TRIM(idempotency_key) <> ''),
    KEY ix_trade_portfolio_executed
        (portfolio_id, executed_at DESC),
    KEY ix_trade_instrument_executed
        (instrument_id, executed_at DESC)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci
  COMMENT = 'Immutable buy/sell business facts; corrections use compensating trades';

-- PORTFOLIO_POSITION is a transactional projection of immutable trade records.
-- The application service must update TRADE_TRANSACTION and PORTFOLIO_POSITION
-- in one database transaction using SELECT ... FOR UPDATE on the affected row.
-- SELL quantity must never exceed the current quantity.
CREATE TABLE IF NOT EXISTS portfolio_position (
    portfolio_id        char(36) NOT NULL,
    instrument_id       char(36) NOT NULL,
    quantity            decimal(28, 8) NOT NULL,
    average_cost        decimal(20, 8) NOT NULL,
    realized_pnl        decimal(20, 8) NOT NULL DEFAULT 0,
    version             int NOT NULL DEFAULT 1,
    opened_at           datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
                        ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (portfolio_id, instrument_id),
    CONSTRAINT fk_position_portfolio
        FOREIGN KEY (portfolio_id)
        REFERENCES portfolio (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_position_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES instrument (id)
        ON DELETE RESTRICT,
    CONSTRAINT position_quantity_nonnegative CHECK (quantity >= 0),
    CONSTRAINT position_average_cost_nonnegative CHECK (average_cost >= 0),
    CONSTRAINT position_version_positive CHECK (version > 0),
    KEY ix_position_instrument (instrument_id)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci
  COMMENT = 'Current long-only position projection maintained by the domain service';

CREATE TABLE IF NOT EXISTS market_data_sync_run (
    id                  char(36) NOT NULL,
    provider            varchar(50) NOT NULL,
    status              enum(
                            'RUNNING',
                            'SUCCEEDED',
                            'PARTIAL',
                            'FAILED'
                        ) NOT NULL DEFAULT 'RUNNING',
    stage               enum(
                            'QUEUED',
                            'FETCHING_MARKET_DATA',
                            'REFRESHING_CURRENT_VALUATIONS',
                            'REBUILDING_HISTORICAL_VALUATIONS',
                            'COMPLETED'
                        ) NOT NULL DEFAULT 'QUEUED',
    requested_count     int NOT NULL DEFAULT 0,
    success_count       int NOT NULL DEFAULT 0,
    failure_count       int NOT NULL DEFAULT 0,
    started_at          datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    completed_at        datetime(6),
    error_summary       text,
    triggered_by        enum('SCHEDULE', 'MANUAL', 'RETRY')
                        NOT NULL DEFAULT 'SCHEDULE',
    PRIMARY KEY (id),
    CONSTRAINT sync_provider_not_blank CHECK (TRIM(provider) <> ''),
    CONSTRAINT sync_requested_nonnegative CHECK (requested_count >= 0),
    CONSTRAINT sync_success_nonnegative CHECK (success_count >= 0),
    CONSTRAINT sync_failure_nonnegative CHECK (failure_count >= 0),
    CONSTRAINT sync_counts_not_above_requested
        CHECK (success_count + failure_count <= requested_count),
    CONSTRAINT sync_completed_after_started
        CHECK (completed_at IS NULL OR completed_at >= started_at),
    KEY ix_sync_run_started (started_at DESC)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS market_price (
    id                  bigint unsigned NOT NULL AUTO_INCREMENT,
    instrument_id       char(36) NOT NULL,
    sync_run_id         char(36),
    price_date          date NOT NULL,
    open_price          decimal(20, 8),
    high_price          decimal(20, 8),
    low_price           decimal(20, 8),
    close_price         decimal(20, 8) NOT NULL,
    adjusted_close      decimal(20, 8),
    volume              decimal(28, 0),
    currency            char(3) NOT NULL DEFAULT 'USD',
    source              varchar(50) NOT NULL,
    source_timestamp    datetime(6),
    fetched_at          datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_market_price_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES instrument (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_market_price_sync_run
        FOREIGN KEY (sync_run_id)
        REFERENCES market_data_sync_run (id)
        ON DELETE SET NULL,
    CONSTRAINT uq_market_price_instrument_date_source
        UNIQUE (instrument_id, price_date, source),
    CONSTRAINT market_price_open_positive
        CHECK (open_price IS NULL OR open_price > 0),
    CONSTRAINT market_price_high_positive
        CHECK (high_price IS NULL OR high_price > 0),
    CONSTRAINT market_price_low_positive
        CHECK (low_price IS NULL OR low_price > 0),
    CONSTRAINT market_price_close_positive CHECK (close_price > 0),
    CONSTRAINT market_price_adjusted_close_positive
        CHECK (adjusted_close IS NULL OR adjusted_close > 0),
    CONSTRAINT market_price_volume_nonnegative
        CHECK (volume IS NULL OR volume >= 0),
    CONSTRAINT market_price_currency_format
        CHECK (
            CHAR_LENGTH(currency) = 3
            AND BINARY currency = BINARY UPPER(currency)
        ),
    CONSTRAINT market_price_source_not_blank
        CHECK (TRIM(source) <> ''),
    CONSTRAINT market_price_high_low_order
        CHECK (
            high_price IS NULL
            OR low_price IS NULL
            OR high_price >= low_price
        ),
    KEY ix_market_price_instrument_latest
        (instrument_id, price_date DESC, fetched_at DESC),
    KEY ix_market_price_sync_run (sync_run_id)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci
  COMMENT = 'Provider-normalized daily OHLCV prices';

CREATE TABLE IF NOT EXISTS market_intraday_bar (
    id              bigint unsigned NOT NULL AUTO_INCREMENT,
    instrument_id   char(36) NOT NULL,
    interval_code   varchar(8) NOT NULL,
    bar_timestamp   datetime(6) NOT NULL,
    open_price      decimal(20, 8) NOT NULL,
    high_price      decimal(20, 8) NOT NULL,
    low_price       decimal(20, 8) NOT NULL,
    close_price     decimal(20, 8) NOT NULL,
    volume          bigint unsigned,
    currency        char(3) NOT NULL,
    source          varchar(40) NOT NULL,
    fetched_at      datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_intraday_bar_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES instrument (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_intraday_bar_identity
        UNIQUE (instrument_id, interval_code, bar_timestamp, source),
    CONSTRAINT intraday_bar_prices_positive
        CHECK (
            open_price > 0
            AND high_price > 0
            AND low_price > 0
            AND close_price > 0
            AND high_price >= low_price
        ),
    KEY ix_intraday_bar_lookup
        (instrument_id, interval_code, bar_timestamp DESC)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci
  COMMENT = 'Provider-normalized intraday OHLCV bars in UTC';

CREATE TABLE IF NOT EXISTS portfolio_valuation_snapshot (
    id                      bigint unsigned NOT NULL AUTO_INCREMENT,
    portfolio_id            char(36) NOT NULL,
    valuation_date          date NOT NULL,
    priced_market_value     decimal(24, 8) NOT NULL,
    total_cost_basis        decimal(24, 8) NOT NULL,
    priced_cost_basis       decimal(24, 8) NOT NULL,
    unrealized_pnl          decimal(24, 8) NOT NULL,
    priced_position_count   int NOT NULL,
    unpriced_position_count int NOT NULL,
    calculated_at           datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_snapshot_portfolio
        FOREIGN KEY (portfolio_id)
        REFERENCES portfolio (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_snapshot_portfolio_date
        UNIQUE (portfolio_id, valuation_date),
    CONSTRAINT snapshot_values_nonnegative
        CHECK (
            priced_market_value >= 0
            AND total_cost_basis >= 0
            AND priced_cost_basis >= 0
        ),
    CONSTRAINT snapshot_counts_nonnegative
        CHECK (
            priced_position_count >= 0
            AND unpriced_position_count >= 0
        ),
    KEY ix_snapshot_portfolio_date
        (portfolio_id, valuation_date DESC)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- MySQL requires separate UPDATE and DELETE triggers.
DROP TRIGGER IF EXISTS trg_trade_transaction_immutable_update;
DROP TRIGGER IF EXISTS trg_trade_transaction_immutable_delete;

DELIMITER $$

CREATE TRIGGER trg_trade_transaction_immutable_update
BEFORE UPDATE ON trade_transaction
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT =
            'trade_transaction rows are immutable; create a compensating trade';
END$$

CREATE TRIGGER trg_trade_transaction_immutable_delete
BEFORE DELETE ON trade_transaction
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT =
            'trade_transaction rows are immutable; create a compensating trade';
END$$

DELIMITER ;

-- Returns one latest successfully persisted daily close per instrument.
-- If two providers have the same date, the most recently fetched row wins.
CREATE OR REPLACE VIEW latest_market_price AS
SELECT
    mp.instrument_id,
    mp.price_date,
    mp.close_price,
    mp.adjusted_close,
    mp.currency,
    mp.source,
    mp.source_timestamp,
    mp.fetched_at
FROM market_price AS mp
WHERE NOT EXISTS (
    SELECT 1
    FROM market_price AS newer
    WHERE newer.instrument_id = mp.instrument_id
      AND (
          newer.price_date > mp.price_date
          OR (
              newer.price_date = mp.price_date
              AND newer.fetched_at > mp.fetched_at
          )
          OR (
              newer.price_date = mp.price_date
              AND newer.fetched_at = mp.fetched_at
              AND newer.id > mp.id
          )
      )
);

-- Position-level authoritative values. The API determines FRESH/STALE using
-- the configured exchange calendar; price_age_days is deliberately exposed.
CREATE OR REPLACE VIEW position_metrics AS
SELECT
    p.portfolio_id,
    p.instrument_id,
    i.symbol,
    i.name AS instrument_name,
    i.asset_type,
    i.exchange_code,
    p.quantity,
    p.average_cost,
    p.realized_pnl,
    p.quantity * p.average_cost AS cost_basis,
    lmp.price_date,
    lmp.close_price,
    lmp.source AS price_source,
    lmp.fetched_at AS price_fetched_at,
    CASE
        WHEN lmp.price_date IS NULL THEN NULL
        ELSE DATEDIFF(UTC_DATE(), lmp.price_date)
    END AS price_age_days,
    CASE
        WHEN lmp.close_price IS NULL THEN NULL
        ELSE p.quantity * lmp.close_price
    END AS market_value,
    CASE
        WHEN lmp.close_price IS NULL THEN NULL
        ELSE (p.quantity * lmp.close_price)
             - (p.quantity * p.average_cost)
    END AS unrealized_pnl,
    CASE
        WHEN lmp.close_price IS NULL
          OR p.quantity * p.average_cost = 0
        THEN NULL
        ELSE (
            ((p.quantity * lmp.close_price)
             - (p.quantity * p.average_cost))
            / (p.quantity * p.average_cost)
        ) * 100
    END AS return_pct
FROM portfolio_position AS p
JOIN instrument AS i
  ON i.id = p.instrument_id
LEFT JOIN latest_market_price AS lmp
  ON lmp.instrument_id = p.instrument_id
WHERE p.quantity > 0;

CREATE OR REPLACE VIEW portfolio_allocation AS
SELECT
    valued.portfolio_id,
    valued.instrument_id,
    valued.symbol,
    valued.instrument_name,
    valued.asset_type,
    valued.quantity,
    valued.close_price,
    valued.price_date,
    valued.price_source,
    valued.market_value,
    CASE
        WHEN valued.market_value IS NULL
          OR valued.portfolio_priced_market_value = 0
        THEN NULL
        ELSE valued.market_value
             / valued.portfolio_priced_market_value
             * 100
    END AS allocation_pct
FROM (
    SELECT
        pm.*,
        SUM(pm.market_value) OVER (
            PARTITION BY pm.portfolio_id
        ) AS portfolio_priced_market_value
    FROM position_metrics AS pm
) AS valued;

CREATE OR REPLACE VIEW portfolio_summary AS
SELECT
    pf.id AS portfolio_id,
    pf.user_id,
    pf.name,
    pf.base_currency,
    COUNT(pm.instrument_id) AS position_count,
    COUNT(pm.market_value) AS priced_position_count,
    COUNT(pm.instrument_id) - COUNT(pm.market_value)
        AS unpriced_position_count,
    COALESCE(SUM(pm.market_value), 0) AS priced_market_value,
    COALESCE(SUM(pm.cost_basis), 0) AS total_cost_basis,
    COALESCE(
        SUM(
            CASE
                WHEN pm.market_value IS NOT NULL THEN pm.cost_basis
                ELSE 0
            END
        ),
        0
    ) AS priced_cost_basis,
    COALESCE(SUM(pm.unrealized_pnl), 0) AS unrealized_pnl,
    CASE
        WHEN COALESCE(
            SUM(
                CASE
                    WHEN pm.market_value IS NOT NULL THEN pm.cost_basis
                    ELSE 0
                END
            ),
            0
        ) = 0
        THEN NULL
        ELSE (
            COALESCE(SUM(pm.unrealized_pnl), 0)
            / SUM(
                CASE
                    WHEN pm.market_value IS NOT NULL THEN pm.cost_basis
                    ELSE 0
                END
            )
        ) * 100
    END AS return_pct,
    MAX(pm.price_date) AS newest_price_date,
    MIN(
        CASE
            WHEN pm.market_value IS NOT NULL THEN pm.price_date
            ELSE NULL
        END
    ) AS oldest_used_price_date
FROM portfolio AS pf
LEFT JOIN position_metrics AS pm
  ON pm.portfolio_id = pf.id
WHERE pf.is_archived = false
GROUP BY
    pf.id,
    pf.user_id,
    pf.name,
    pf.base_currency;
